// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABuqIaMggAFrvY3QfA3dj3-a1Kmpyy9ZI',
    appId: '1:381153402196:web:8734a5c9f02e99050ffcc1',
    messagingSenderId: '381153402196',
    projectId: 'flashchat-949d5',
    authDomain: 'flashchat-949d5.firebaseapp.com',
    storageBucket: 'flashchat-949d5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjWZHhp2OQAga09eHRWHF99wHquDqS1ck',
    appId: '1:381153402196:android:d2c3dbfdf6777aea0ffcc1',
    messagingSenderId: '381153402196',
    projectId: 'flashchat-949d5',
    storageBucket: 'flashchat-949d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBMNMOoOI5QgVPPn9dHziVBrSAk0hPDLw',
    appId: '1:381153402196:ios:5917a60d67b3948b0ffcc1',
    messagingSenderId: '381153402196',
    projectId: 'flashchat-949d5',
    storageBucket: 'flashchat-949d5.appspot.com',
    iosClientId: '381153402196-c4huef8ctmrb4876vo26mu7fgaooaecl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBMNMOoOI5QgVPPn9dHziVBrSAk0hPDLw',
    appId: '1:381153402196:ios:669784317eff76790ffcc1',
    messagingSenderId: '381153402196',
    projectId: 'flashchat-949d5',
    storageBucket: 'flashchat-949d5.appspot.com',
    iosClientId: '381153402196-eed12e84vjdqob7554q1upfs3sbfpcoc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat.RunnerTests',
  );
}
